config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'

  resources :movies
  resources :users, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u|
      u.permit(:password, :password_confirmatioin, :current_password)
    }
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :set_movie, only: [:show, :destroy, :edit, :update]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to @movie, notice: 'Movie was successfully created'
    else
      render :new, flash[:error] = 'Movie was not created'
    end
  end
  
  def show
  end

  private
  
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :director, :year, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_controllers_helper.rb
module UsersControllersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MoviePicker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Movie', root_url, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path  %></li>
              <li><%= link_to "Login", new_user_session_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Protchenko 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for (@movie) do |f| %>

 <div class="form-group">
   <%= f.label 'Title:' %>
   <%= f.text_field :title, class: 'form-control' %>
</div>

 <div class="form-group">
   <%= f.label 'Director' %>
   <%= f.text_field :director, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label 'Released:' %>
   <%= f.text_field :year, class: 'form-control' %>
 </div>

 <div class="form-group">
   <%= f.label 'Description:' %>
   <%= f.text_area :description, class: 'form-control' %>
 </div>

 <div class="actions">
   <%= f.submit class: 'btn btn-info' %> or <%= link_to 'back', :back %>
 </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">

    <%= content_tag 'div', '',
                    class: 'movie-background',
                    style: "background-image: url(#{asset_path('movie_thumb.png')})"
    %>

    <div class="thumbnail-inner movie-info-inner">
      <div class="caption">
        <div class="movie-description">
          <h3><%= link_to movie.title, movie_path(movie) %></h3>
          <h3>
            <small>Director: <%= movie.director %></small>
            <small>Released: <%= movie.year %></small>
            <p>Description:</p>
          </h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/index.html.erb
<h1>New movies</h1>

  <div class="row buffer-both">
    <%= render partial: 'movies/movie', collection: @movies %>
  </div>

  <div class="actions">
    <%= link_to 'Create movie', new_movie_path, class: 'btn btn-info' %>
  </div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<h1>Movie</h1>

<% if @movie.present? %>
  <h3><%= @movie.title %></h3>
  <p>Director:&nbsp<%= @movie.director %></p>
  <p>Released:&nbsp<%= @movie.year %> year</p>
  <p>Description: <%= @movie.description %></p>
<% else %>
  <h4>Sorry, unfortunately there is no movie</h4>
<% end %>

<%= link_to 'Back to movies', movies_path, class: 'btn btn-default' %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', user_path(@user) %> |
<%= link_to 'Back', :back %>

app/views/users/show.html.erb
<div class="text-center">
  <%= image_tag('', alt: 'No fucking photo') %>
  <%= mail_to @user.email %>
  <%= link_to 'Edit', edit_user_registration_path(@user) %> |
  <%= link_to 'Back', :back %>
</div>